### ISSUE TITLE
expo-facebook Native method ExponentFacebook.loginWithReadPermissionsAsync expected 2 arguments but received 1

### ISSUE THREAD

**Issue by hereblur** [unimodules/react-native-unimodules#99]
I follow expo document  and install expo-facebook. but If got this exception  when click on Login.

`ExponentFacebook.loginWithReadPermissionsAsync expected 2 arguments but received 1`

The document said to pass only 1 arguments "option" which is object. I dont know what's the second arguments should I pass?

 I checked the code and found that 
```
@ExpoMethod
  public void logInWithReadPermissionsAsync(final ReadableArguments config, final Promise promise) {
```
Normally It should return `Promise` for me not I pass to it. What I did wrong?

**Comment by mortexe** [comment]
Experiencing the same issue, came across a solution for this?

**Comment by AngSin** [comment]
I was getting this error, realised I was using expo SDK version 35. Did `expo upgrade` and it was fixed.

**Comment by sjchmiela** [comment]
The `Promise` there, passed as an argument, is ok and is injected automatically. The problem you're experiencing should have more to do with the difference between native code version and JS version. Are you sure you have rebuilt your native app after upgrading the library? And if you're using Expo client to develop your app, that `expo-facebook` version matches the one expected by the SDK?

**Comment by jazeb786** [comment]
Experiencing the same issue, any solution for resolve this issue ?

**Comment by sjchmiela** [comment]
Hey, sorry for late response — is the issue still relevant? I believe this shouldn't occur for matching versions of native and JS code, `expo-facebook@7.0.0` passes two arguments to the native module:
